### ISSUE TITLE
State of CSS TODO

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#188]
### Demographics

- [ ] Participation by Country
- [ ] Salaries
- [ ] Average Salary per Country
- [ ] Years of Experience
- [ ] Company Size
- [ ] Source Breakdown
- [ ] Gender Breakdown

### Features Overview Template

- [ ] Intro
- [ ] Overall scatterplot?
- [ ] Top 20 most used
- [ ] Top 20 least used

#### Introduction

- [ ] Make intros shorter

#### Scatterplot

- [ ] Weird to have % vs absolute units?
- [ ] Add labels
- [ ] Make axes easier to understand

#### Feature Blocks

- [ ] Use waffle charts?

### Units & Selectors

- [ ] vertical bar chart rankings

### Tools & Methodologies

- [ ] Overview (stacked bar chart?)
- [ ] Tool blocks (waffle chart?)
- [ ] Other answers
- [ ] Salary
- [ ] Experience
- [ ] Company size
- [ ] Usage by country (?)

**Comment by SachaG** [comment]
Misc questions/issues:

- [ ] why is `labelTextColor` set on `ResponsiveBar` props instead of coming from theme?
- [ ] why is font family specified in theme?
- [ ] should years of experience, company size, etc. all be refactored into the same component instead of all having separate files?
- [ ] refactor `SalaryPerCountryMapChart` and `ParticipationByCountryMapChart` into same component?

**Comment by plouc** [comment]
- `labelTextColor` can inherit from bar color, theme or be a static color, that's why.
- font family is defined in theme because canvas doesn't care about stylesheets :)
- Maps could use the new `@nivo/geo` package's `Choropleth` component

**Comment by plouc** [comment]
Refactoring `years of experience`, `company size`, … means using an abstract bar component, I'm not sure it could be useful VS using nivo Bar with predefined options

**Comment by plouc** [comment]
Regarding `labelTextColor`, please have a look at [this guide](https://nivo.rocks/guides/colors) (*Single color property*)

**Comment by SachaG** [comment]
Regarding refactoring, I think the biggest thing we're missing is some kind of generic block and component for things like bar charts. Looking at `DemographicsSalaryBlock` for example, I don't see why it needs to have its own component?

And then same thing with `DemographicsVerticalBarChart`, it could just be a generic `VerticalBarChart`?

**Comment by SachaG** [comment]
- [ ] Where do we get the tools descriptions (`block.sass.description`) from? If it's not automated, we might as well remove them?
- [ ] Browsers/Form Factors/resources/etc.: can we combine main options with "other" option in a single chart?

**Comment by SachaG** [comment]
- [ ] Is it useful to specify blocks in the raw sitemap for pages like Demographics since we also list them out in the component itself? Isn't that redundant?

**Comment by SachaG** [comment]
- [ ] We need to harmonize names between the sitemap and data. For example the sitemap uses `company-size` but the data has `company_size`

**Comment by plouc** [comment]
Yes, because we wanted to use `company-size` for urls, but it's not valid in elasticsearch

**Comment by SachaG** [comment]
- [ ] It's also a little inconvenient that the data isn't always nested under the same property name. For example salary data is at `salary.ranges` but source data is at `sources.by_source`.

**Comment by SachaG** [comment]
- [ ] Another related issue: do we want to compute just the data relevant to a single block first and then pass that to the block; or else pass the entire page's data to the block and let it extract the relevant data? Currently we're doing approach #2 but it feels a little messier maybe…?

**Comment by plouc** [comment]
We could use the same terminology as elasticsearch which use the `buckets` property, but I liked to have more meaningful names :) It might be easier when consuming the data for a single chart, but when manipulating it, it's really unpractical

**Comment by plouc** [comment]
I prefer the first approach, isolating the block's data, unless we have blocks which depends on each other
