### ISSUE TITLE
v1.1

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#44]
### To-do

- [ ] Add percents to charts
- [ ] Opinions
- [ ] Features

### Nice-to-have

- [ ] Per-country salaries
- [ ] Provide anonymized data as csv
